"""The optional LLM path, tested with a fake Ollama server (no model needed)."""
import httpx
import pytest

from app.core.config import get_settings
from app.graph.builder import ArchitectureGraph
from app.rag.answerer import NOT_FOUND, GroundedAnswerer
from app.rag.retriever import BM25Retriever

CHUNKS = [{"chunk_id": "c1", "text": "DoorControl provides IDoorStatus to BodyControlManager.",
           "page_number": 2, "section": "4. Interfaces"}]


class FakeResponse:
    def __init__(self, text):
        self._text = text

    def raise_for_status(self):
        pass

    def json(self):
        return {"response": self._text}


@pytest.fixture
def answerer(monkeypatch):
    settings = get_settings()
    monkeypatch.setattr(settings, "llm_provider", "ollama")
    monkeypatch.setattr(settings, "llm_model", "llama3.2")
    monkeypatch.setattr(settings, "answerability_model_dir", "/nonexistent")
    from app.rag.answerability import load_answerability_model
    load_answerability_model.cache_clear()
    yield GroundedAnswerer(BM25Retriever(CHUNKS), ArchitectureGraph(), "doc", "v1")
    load_answerability_model.cache_clear()


def test_llm_text_is_used_and_labelled(answerer, monkeypatch):
    seen = {}

    def fake_post(url, json=None, **kw):
        seen["url"], seen["prompt"] = url, json["prompt"]
        return FakeResponse("DoorControl provides IDoorStatus [C1].")

    monkeypatch.setattr(httpx, "post", fake_post)
    r = answerer.answer("Which component provides IDoorStatus?")
    assert r.answer == "DoorControl provides IDoorStatus [C1]."
    assert r.generated_by == "ollama:llama3.2"
    assert "/api/generate" in seen["url"]
    assert "ONLY the evidence" in seen["prompt"] and "DoorControl provides IDoorStatus" in seen["prompt"]
    assert any("generated by ollama" in lim for lim in r.limitations)
    assert r.citations  # citations still come from retrieval, not from the LLM


def test_llm_failure_falls_back_to_extractive(answerer, monkeypatch):
    def boom(*a, **kw):
        raise httpx.ConnectError("ollama is not running")

    monkeypatch.setattr(httpx, "post", boom)
    r = answerer.answer("Which component provides IDoorStatus?")
    assert r.generated_by is None and "Relevant document text" in r.answer


def test_llm_not_found_reply_falls_back(answerer, monkeypatch):
    monkeypatch.setattr(httpx, "post", lambda *a, **kw: FakeResponse(NOT_FOUND))
    r = answerer.answer("Which component provides IDoorStatus?")
    assert r.generated_by is None and r.answer != NOT_FOUND


def test_default_provider_never_calls_a_model(monkeypatch):
    def forbidden(*a, **kw):
        raise AssertionError("no network call expected when LLM_PROVIDER=local")

    monkeypatch.setattr(httpx, "post", forbidden)
    monkeypatch.setattr(get_settings(), "llm_provider", "local")
    a = GroundedAnswerer(BM25Retriever(CHUNKS), ArchitectureGraph(), "doc", "v1")
    assert a.answer("Which component provides IDoorStatus?").generated_by is None
